# Site settings
title: GetJob
description: AI 기반 IT 직군 취업 지원 플랫폼
baseurl: ""
url: "https://jinsoru1464.github.io"

# Build settings
markdown: kramdown
permalink: /:title/

# Author Settings
author:
  name: JinSol Lee, JinWoo Park, YeonSoo Eom
  affiliation: Soongsil University
  email: ""

# Social Links
social:
  github: https://github.com/jinsoru1464/GetJob
  website: https://getjob.world

# Analytics (원하면)
# google_analytics: G-XXXXXXXXXX

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
